# Site settings
author: Nick Stewart
title: Why I chose to be a software engineer 
header-img: img/home-bg.png
email: jnicklausstewart@yahoo.com
copyright_name: Nick Stewart
description: > # this means to ignore newlines until "baseurl:"
  Software Engineering
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  nick-stew

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
